# baseURL = 'http://example.org/'
baseURL = 'https://guillesanchez.com/'
languageCode = 'en-us'
theme = 'graysx'
title = 'Guille Sanchez Portfolio | Programming - Game Dev - Illustration'


## Site Settings
[params]
logo = "images/logo3.webp"
favicon = "images/favicon.png"
resumeURL = "/files/resume-2025.pdf"

# Info
address = "SP"
email = "guillekm92@gmail.com"
phone = "123456"

# Socials

twitter = "#"
facebook = "#"
github = "https://guillesanchez.com/"

# Other

# Startbootstrap Contact Form Token https://startbootstrap.com/solution/contact-forms
sbtoken = "TOKEN_HERE"

## Menu Items
[menu]
  [[menu.main]]
  name = "About"
  URL = "/#about"
  weight = 1

  [[menu.main]]
  name = "Skills"
  URL = "/#skills"
  weight = 2

  [[menu.main]]
  name = "Projects"
  URL = "/#projects"
  weight = 3

  [[menu.main]]
  name = "Contact"
  URL = "/#contact"
  weight = 4

  [[menu.secondary]]
  name = "Resume"
  # URL = "/#projects"
  # URL = "/files/resume.pdf"
  # URL = "/files/resume-2025.pdf"
  weight = 5


# Credits

# This theme is forked from: https://github.com/startbootstrap/startbootstrap-grayscale
# This theme is forked by: https://github.com/akatiggerx04